#!/usr/bin/env python3
"""Regenerate src/data/gallery.ts from public/gallery/manifest.json.

Run after scripts/optimize_gallery.py, which writes the manifest. Categories and
display titles are derived from each photo's descriptive slug, so adding photos
only means naming them in optimize_gallery.py and re-running both scripts.

Usage:  python3 scripts/generate_gallery_data.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
m = json.loads((ROOT / 'public/gallery/manifest.json').read_text())

# Order matters: first match wins.
RULES = [
    ('fire-pits',          ('fire-pit', 'fireplace', 'fire-feature', 'fire-bowl')),
    ('artificial-turf',    ('turf', 'putting-green')),
    ('outdoor-living',     ('outdoor-kitchen', 'pergola', 'cabana', 'string-lights',
                            'lounge-seating', 'bench-seating', 'statuary')),
    ('water-features',     ('waterfall', 'sheer-descent', 'grotto', 'deck-jets',
                            'spillway', 'water-feature', 'slide')),
    ('pool-construction',  ('pool', 'spa')),
    ('concrete-driveways', ('driveway', 'concrete-patio', 'walkway', 'paver')),
]

# Lead photos, in order. These open the grid regardless of alphabetical
# position, so the strongest work is what a visitor sees first.
FEATURED = [
    'pinnacle-pools-pool-water-features-landscape-lighting-night',
    'pinnacle-pools-pool-step-tile-mosaic-detail',
    'pinnacle-pools-outdoor-fireplace-fire-pit-seating-pool',
]


def category(slug: str) -> str:
    s = slug.replace('pinnacle-pools-', '')
    for cat, keys in RULES:
        if any(k in s for k in keys):
            return cat
    return 'landscaping'

def title(slug: str) -> str:
    words = slug.replace('pinnacle-pools-', '').replace('-', ' ')
    small = {'and', 'with', 'on', 'in', 'at'}
    caps = {'led': 'LED', 'bbq': 'BBQ'}
    out = []
    for i, w in enumerate(words.split()):
        if w in caps: out.append(caps[w])
        elif i and w in small: out.append(w)
        else: out.append(w.capitalize())
    return ' '.join(out)

rows = []
def sort_key(entry):
    slug = entry['slug']
    rank = FEATURED.index(slug) if slug in FEATURED else len(FEATURED)
    return (rank, slug)


for e in sorted(m, key=sort_key):
    grid = min(e['srcset'], key=lambda s: s['width'])
    wide = max(e['srcset'], key=lambda s: s['width'])
    rows.append({
        'slug': e['slug'],
        'src': grid['src'],
        'fallback': e['fallback'],
        'width': grid['width'],
        'height': grid['height'],
        'wideSrc': wide['src'] if wide['src'] != grid['src'] else None,
        'wideWidth': wide['width'],
        'alt': e['alt'],
        'title': title(e['slug']),
        'category': category(e['slug']),
    })

missing = [f for f in FEATURED if f not in {e['slug'] for e in m}]
if missing:
    raise SystemExit(f'FEATURED slug not in manifest: {missing}')

order = ['pool-construction', 'water-features', 'fire-pits', 'outdoor-living',
         'artificial-turf', 'concrete-driveways', 'landscaping']
labels = {
    'pool-construction': 'Pools & Spas',
    'water-features': 'Water Features',
    'fire-pits': 'Fire Pits & Fireplaces',
    'outdoor-living': 'Outdoor Living',
    'artificial-turf': 'Artificial Turf',
    'concrete-driveways': 'Concrete & Hardscape',
    'landscaping': 'Landscaping',
}
present = [c for c in order if any(r['category'] == c for r in rows)]

def ts(v):
    if v is None: return 'undefined'
    if isinstance(v, str): return '"' + v.replace('"', '\\"') + '"'
    return str(v)

lines = [
    '// Generated by scripts/generate_gallery_data.py from public/gallery/manifest.json.',
    '// Edit the manifest (or re-run scripts/optimize_gallery.py) rather than this file by hand.',
    '',
    'export type GalleryCategory =',
    *[f'  | "{c}"' for c in present],
    '  ;'.replace('  ;', '  ;'),
    '',
    'export type GalleryImage = {',
    '  /** Descriptive, SEO-bearing slug; also the React key. */',
    '  slug: string;',
    '  /** WebP at grid width (1200px nominal). */',
    '  src: string;',
    '  /** JPEG fallback at the same width. */',
    '  fallback: string;',
    '  width: number;',
    '  height: number;',
    '  /** Larger WebP for lightbox/hero use, when the source was big enough. */',
    '  wideSrc?: string;',
    '  wideWidth?: number;',
    '  alt: string;',
    '  title: string;',
    '  category: GalleryCategory;',
    '};',
    '',
    'export const galleryImages: GalleryImage[] = [',
]
for r in rows:
    parts = [f'slug: {ts(r["slug"])}', f'src: {ts(r["src"])}', f'fallback: {ts(r["fallback"])}',
             f'width: {r["width"]}', f'height: {r["height"]}']
    if r['wideSrc']:
        parts += [f'wideSrc: {ts(r["wideSrc"])}', f'wideWidth: {r["wideWidth"]}']
    parts += [f'alt: {ts(r["alt"])}', f'title: {ts(r["title"])}', f'category: {ts(r["category"])}']
    lines.append('  { ' + ', '.join(parts) + ' },')
lines += [
    '];',
    '',
    'export const galleryCategories = [',
    '  { slug: "all", label: "All Projects" },',
    *[f'  {{ slug: "{c}", label: "{labels[c]}" }},' for c in present],
    '] as const;',
    '',
]
out = '\n'.join(lines)
# fix the union terminator
out = out.replace('\n  ;\n', ';\n', 1)
out = out.replace('export type GalleryCategory =\n  | "', 'export type GalleryCategory =\n  | "')
(ROOT / 'src/data/gallery.ts').write_text(out)

import collections
print(collections.Counter(r['category'] for r in rows))
print(f'{len(rows)} images written')
